/*
- 각 호선마다 배열로 설정
- 각 호선마다 해당되는 역을 배열에 저장
- 중복 호선이 있을 경우 중복 저장 (ex: 동대문역 → 1호선, 4호선)
- 각 호선마다 일치하는 아이콘 경로 설정
*/

const stations = {
  line1: [
    { name: '서울역', line: 'Line_1', icon: 'Line_1.png' },
    { name: '종각', line: 'Line_1', icon: 'Line_1.png' },
    { name: '종로3가', line: 'Line_1', icon: 'Line_1.png' },
    { name: '종로5가', line: 'Line_1', icon: 'Line_1.png' },
    { name: '동대문', line: 'Line_1', icon: 'Line_1.png' },
    { name: '신설동', line: 'Line_1', icon: 'Line_1.png' },
    { name: '제기동', line: 'Line_1', icon: 'Line_1.png' },
    { name: '청량리', line: 'Line_1', icon: 'Line_1.png' },
    { name: '회기', line: 'Line_1', icon: 'Line_1.png' },
    { name: '외대앞', line: 'Line_1', icon: 'Line_1.png' },
    { name: '온수', line: 'Line_1', icon: 'Line_1.png' },
    { name: '오류동', line: 'Line_1', icon: 'Line_1.png' },
    { name: '개봉', line: 'Line_1', icon: 'Line_1.png' },
    { name: '구일', line: 'Line_1', icon: 'Line_1.png' },
    { name: '금천구청', line: 'Line_1', icon: 'Line_1.png' },
    { name: '독산', line: 'Line_1', icon: 'Line_1.png' },
    { name: '가산디지털단지', line: 'Line_1', icon: 'Line_1.png' },
    { name: '구로', line: 'Line_1', icon: 'Line_1.png' },
    { name: '신도림', line: 'Line_1', icon: 'Line_1.png' },
    { name: '영등포', line: 'Line_1', icon: 'Line_1.png' },
    { name: '신길', line: 'Line_1', icon: 'Line_1.png' },
    { name: '대방', line: 'Line_1', icon: 'Line_1.png' },
    { name: '노량진', line: 'Line_1', icon: 'Line_1.png' },
    { name: '용산', line: 'Line_1', icon: 'Line_1.png' },
    { name: '시청', line: 'Line_1', icon: 'Line_1.png' },
    { name: '동묘앞', line: 'Line_1', icon: 'Line_1.png' },
    { name: '신이문', line: 'Line_1', icon: 'Line_1.png' },
    { name: '석계', line: 'Line_1', icon: 'Line_1.png' },
    { name: '광운대', line: 'Line_1', icon: 'Line_1.png' },
    { name: '월계', line: 'Line_1', icon: 'Line_1.png' },
    { name: '녹천', line: 'Line_1', icon: 'Line_1.png' },
    { name: '창동', line: 'Line_1', icon: 'Line_1.png' },
    { name: '방학', line: 'Line_1', icon: 'Line_1.png' },
    { name: '도봉', line: 'Line_1', icon: 'Line_1.png' },
    { name: '도봉산', line: 'Line_1', icon: 'Line_1.png' }
  ],

  line2: [
    { name: '시청', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '을지로입구', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '을지로3가', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '을지로4가', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '동대문역사문화공원', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '신당', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '상왕십리', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '왕십리', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '한양대', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '뚝섬', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '까치산', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '신정네거리', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '양천구청', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '도림천', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '신도림', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '문래', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '영등포구청', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '당산', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '합정', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '홍대입구', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '신촌', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '이대', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '아현', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '충정로', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '성수', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '용답', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '신답', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '용두', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '건대입구', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '구의', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '강변', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '잠실나루', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '잠실', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '잠실새내', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '종합운동장', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '삼성', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '선릉', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '역삼', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '강남', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '교대', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '서초', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '방배', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '사당', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '낙성대', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '서울대입구', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '봉천', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '신림', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '신대방', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '구로 디지털단지', line: 'Line_2', icon: 'Line_2.svg' },
    { name: '대림', line: 'Line_2', icon: 'Line_2.svg' }
  ],

  line3: [
    { name: '연신내', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '불광', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '녹번', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '홍제', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '무악재', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '독립문', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '경복궁', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '안국', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '종로3가', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '을지로3가', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '충무로', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '동대입구', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '약수', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '금호', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '옥수', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '압구정', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '신사', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '잠원', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '고속터미널', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '교대', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '남부터미널', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '양재', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '매봉', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '도곡', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '대치', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '학여울', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '대청', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '일원', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '가락시장', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '수서', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '경찰병원', line: 'Line_3', icon: 'Line_3.svg' },
    { name: '오금', line: 'Line_3', icon: 'Line_3.svg' }
  ],

  line4: [
    { name: '당고개', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '상계', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '노원', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '창동', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '쌍문', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '수유', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '미아', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '미아사거리', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '길음', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '성신여대입구', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '남태령', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '사당', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '총신대입구(이수)', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '동작', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '이촌', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '신용산', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '삼각지', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '숙대입구', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '서울역', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '회현', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '명동', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '충무로', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '동대문역사문화공원', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '동대문', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '혜화', line: 'Line_4', icon: 'Line_4.svg' },
    { name: '한성대입구', line: 'Line_4', icon: 'Line_4.svg' }
  ],

  line5: [
    { name: '방화', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '개화산', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '김포공항', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '송정', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '마곡', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '발산', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '우장산', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '화곡', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '까치산', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '신정', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '목동', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '오목교', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '양평', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '영등포시장', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '신길', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '여의도', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '여의나루', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '마포', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '공덕', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '애오개', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '서대문', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '광화문', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '청구', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '신금호', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '행당', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '왕십리', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '마장', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '답십리', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '장한평', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '군자', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '아차산', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '광나루', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '천호', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '강동', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '둔촌동', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '올림픽공원', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '방이', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '개롱', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '거여', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '마천', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '길동', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '굽은다리', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '명일', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '고덕', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '상일동', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '강일', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '동대문역사문화공원', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '종로3가', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '을지로3가', line: 'Line_5', icon: 'Line_5.svg' },
    { name: '오금', line: 'Line_5', icon: 'Line_5.svg' }
  ],

  line6: [
    { name: '봉화산', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '화랑대', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '태릉입구', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '석계', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '돌곶이', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '상월곡', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '월곡', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '고려대', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '안암', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '보문', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '연신내', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '독바위', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '불광', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '역촌', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '구산', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '응암', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '새절', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '증산', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '디지털 미디어시티', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '월드컵 경기장', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '마포구청', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '망원', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '합정', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '상수', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '광흥창', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '대흥', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '공덕', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '효창공원앞', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '삼각지', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '녹사평', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '이태원', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '한강진', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '버티고개', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '약수', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '청구', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '신당', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '동묘앞', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '창신', line: 'Line_6', icon: 'Line_6.svg' },
    { name: '신내', line: 'Line_6', icon: 'Line_6.svg' }
  ],

  line7: [
    { name: '장암', line: 'Line_7', icon: 'Line_7.png' },
    { name: '도봉산', line: 'Line_7', icon: 'Line_7.png' },
    { name: '수락산', line: 'Line_7', icon: 'Line_7.png' },
    { name: '마들', line: 'Line_7', icon: 'Line_7.png' },
    { name: '노원', line: 'Line_7', icon: 'Line_7.png' },
    { name: '중계', line: 'Line_7', icon: 'Line_7.png' },
    { name: '하계', line: 'Line_7', icon: 'Line_7.png' },
    { name: '공릉', line: 'Line_7', icon: 'Line_7.png' },
    { name: '태릉입구', line: 'Line_7', icon: 'Line_7.png' },
    { name: '먹골', line: 'Line_7', icon: 'Line_7.png' },
    { name: '온수', line: 'Line_7', icon: 'Line_7.png' },
    { name: '천왕', line: 'Line_7', icon: 'Line_7.png' },
    { name: '가산디지털단지', line: 'Line_7', icon: 'Line_7.png' },
    { name: '남구로', line: 'Line_7', icon: 'Line_7.png' },
    { name: '대림', line: 'Line_7', icon: 'Line_7.png' },
    { name: '신풍', line: 'Line_7', icon: 'Line_7.png' },
    { name: '보라매', line: 'Line_7', icon: 'Line_7.png' },
    { name: '신대방삼거리', line: 'Line_7', icon: 'Line_7.png' },
    { name: '장승배기', line: 'Line_7', icon: 'Line_7.png' },
    { name: '숭실대입구', line: 'Line_7', icon: 'Line_7.png' },
    { name: '남성', line: 'Line_7', icon: 'Line_7.png' },
    { name: '총신대입구(이수)', line: 'Line_7', icon: 'Line_7.png' },
    { name: '내방', line: 'Line_7', icon: 'Line_7.png' },
    { name: '고속터미널', line: 'Line_7', icon: 'Line_7.png' },
    { name: '반포', line: 'Line_7', icon: 'Line_7.png' },
    { name: '논현', line: 'Line_7', icon: 'Line_7.png' },
    { name: '학동', line: 'Line_7', icon: 'Line_7.png' },
    { name: '강남구청', line: 'Line_7', icon: 'Line_7.png' },
    { name: '청담', line: 'Line_7', icon: 'Line_7.png' },
    { name: '자양', line: 'Line_7', icon: 'Line_7.png' },
    { name: '건대입구', line: 'Line_7', icon: 'Line_7.png' },
    { name: '어린이대공원', line: 'Line_7', icon: 'Line_7.png' },
    { name: '군자', line: 'Line_7', icon: 'Line_7.png' },
    { name: '중곡', line: 'Line_7', icon: 'Line_7.png' },
    { name: '용마산', line: 'Line_7', icon: 'Line_7.png' },
    { name: '사가정', line: 'Line_7', icon: 'Line_7.png' },
    { name: '면목', line: 'Line_7', icon: 'Line_7.png' },
    { name: '상봉', line: 'Line_7', icon: 'Line_7.png' },
    { name: '중화', line: 'Line_7', icon: 'Line_7.png' }
  ],

  line8: [
    { name: '암사', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '천호', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '강동구청', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '몽촌토성', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '잠실', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '석촌', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '송파', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '가락시장', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '문정', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '장지', line: 'Line_8', icon: 'Line_8.svg' },
    { name: '암사역사공원', line: 'Line_8', icon: 'Line_8.svg' }
  ],

  line9: [
    { name: '개화', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '김포공항', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '공항시장', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '신방화', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '마곡나루', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '양천향교', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '가양', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '증미', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '등촌', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '염창', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '신목동', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '선유도', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '당산', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '국회의사당', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '여의도', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '샛강', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '노량진', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '노들', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '흑석', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '동작', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '구반포', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '신반포', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '고속터미널', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '사평', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '신논현', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '언주', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '선정릉', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '삼성중앙', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '봉은사', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '종합운동장', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '삼전', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '석촌고분', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '석촌', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '송파나루', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '한성백제', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '올림픽공원', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '둔춘오륜', line: 'Line_9', icon: 'Line_9.svg' },
    { name: '중앙보훈병원', line: 'Line_9', icon: 'Line_9.svg' }
  ],

  airport: [
    { name: '김포공항', line: 'Airport', icon: 'Airport.svg' },
    { name: '마곡나루', line: 'Airport', icon: 'Airport.svg' },
    { name: '디지털미디어시티', line: 'Airport', icon: 'Airport.svg' },
    { name: '홍대입구', line: 'Airport', icon: 'Airport.svg' },
    { name: '공덕', line: 'Airport', icon: 'Airport.svg' },
    { name: '서울역', line: 'Airport', icon: 'Airport.svg' }
  ],

  gyeong_ui: [
    { name: '수색', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '디지털미디어시티', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '가좌', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '신촌', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '서울역', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '홍대입구', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '서강대', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '공덕', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '효창공원앞', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '용산', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '이촌', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '서빙고', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '한남', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '옥수', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '응봉', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '왕십리', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '청량리', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '회기', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '중랑', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '상봉', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' },
    { name: '망우', line: 'Gyeong_Ui', icon: 'gyeong_ui.svg' }
  ],

  gyeong_chun: [
    { name: '청량리', line: 'Gyeong_Chun', icon: 'gyeong_chun.svg' },
    { name: '회기', line: 'Gyeong_Chun', icon: 'gyeong_chun.svg' },
    { name: '중랑', line: 'Gyeong_Chun', icon: 'gyeong_chun.svg' },
    { name: '광운대', line: 'Gyeong_Chun', icon: 'gyeong_chun.svg' },
    { name: '상봉', line: 'Gyeong_Chun', icon: 'gyeong_chun.svg' },
    { name: '망우', line: 'Gyeong_Chun', icon: 'gyeong_chun.svg' },
    { name: '신내', line: 'Gyeong_Chun', icon: 'gyeong_chun.svg' }
  ],

  soo_in_bundang: [
    { name: '청량리', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '왕십리', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '서울숲', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '압구정로데오', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '강남구청', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '선정릉', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '선릉', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '도곡', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '구룡', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '개포동', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '대모산입구', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '수서', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' },
    { name: '복정', line: 'Soo_In_Bundang', icon: 'old_bundang.svg' }
  ],

  shin_bundang: [
    { name: '청계산입구', line: 'Shin_Bundang', icon: 'new_bundang.svg' },
    { name: '양재시민의숲', line: 'Shin_Bundang', icon: 'new_bundang.svg' },
    { name: '양재', line: 'Shin_Bundang', icon: 'new_bundang.svg' },
    { name: '강남', line: 'Shin_Bundang', icon: 'new_bundang.svg' },
    { name: '신논현', line: 'Shin_Bundang', icon: 'new_bundang.svg' },
    { name: '논현', line: 'Shin_Bundang', icon: 'new_bundang.svg' },
    { name: '신사', line: 'Shin_Bundang', icon: 'new_bundang.svg' }
  ],

  west_sea: [
    { name: '김포공항', line: 'West_Sea', icon: 'west_sea.svg' }
  ],

  woo_e: [
    { name: '신설동', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '보문', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '성신여대입구', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '정릉', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '북한산보국문', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '솔샘', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '삼양사거리', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '삼양', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '화계', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '가오리', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '4.19민주묘지', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '솔밭공원', line: 'Woo_E', icon: 'woo_e.svg' },
    { name: '북한산우이', line: 'Woo_E', icon: 'woo_e.svg' }
  ],

  gold: [
    { name: '김포공항', line: 'Gold', icon: 'gold.png' }
  ],

  shin_lim: [
    { name: '샛강', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '대방', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '서울지방병무청', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '보라매', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '보라매공원', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '보라매병원', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '당곡', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '신림', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '서원', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '서울대밴처타운', line: 'Shin_Lim', icon: 'shin_lim.svg' },
    { name: '관악산', line: 'Shin_Lim', icon: 'shin_lim.svg' }
  ],

  gtx_a: [
    { name: '수서', line: 'GTX_A', icon: 'GTA_A.svg' }
  ]
};

export default stations;